module.exports = {
  apps: [
    {
      name: "tradereplay-backend",
      script: "tsx",
      args: "src/server.ts",
      cwd: "/opt/tradereplay/backend",
      instances: 1,
      exec_mode: "fork",
      env_file: "/opt/tradereplay/.env",
      env: {
        NODE_ENV: "production",
      },
      max_memory_restart: "300M",
      restart_delay: 3000,
      max_restarts: 10,
      autorestart: true,
      watch: false,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      error_file: "/var/log/tradereplay/error.log",
      out_file: "/var/log/tradereplay/out.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "tradereplay-worker",
      script: "tsx",
      args: "src/worker.ts",
      cwd: "/opt/tradereplay/backend",
      instances: Number(process.env.WORKER_INSTANCES || 1),
      exec_mode: "fork",
      env_file: "/opt/tradereplay/.env",
      env: {
        NODE_ENV: "production",
      },
      max_memory_restart: "300M",
      restart_delay: 3000,
      max_restarts: 10,
      autorestart: true,
      watch: false,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      error_file: "/var/log/tradereplay/worker-error.log",
      out_file: "/var/log/tradereplay/worker-out.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "tradereplay-logo-service",
      script: "tsx",
      args: "src/index.ts",
      cwd: "/opt/tradereplay/services/logo-service",
      instances: Number(process.env.LOGO_SERVICE_INSTANCES || 1),
      exec_mode: "fork",
      env_file: "/opt/tradereplay/.env",
      env: {
        NODE_ENV: "production",
      },
      max_memory_restart: "300M",
      restart_delay: 3000,
      max_restarts: 10,
      autorestart: true,
      watch: false,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      error_file: "/var/log/tradereplay/logo-service-error.log",
      out_file: "/var/log/tradereplay/logo-service-out.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "tradereplay-kafka-service",
      script: "tsx",
      args: "src/kafkaService.ts",
      cwd: "/opt/tradereplay/backend",
      instances: 1,
      exec_mode: "fork",
      env_file: "/opt/tradereplay/.env",
      env: {
        NODE_ENV: "production",
      },
      max_memory_restart: "300M",
      restart_delay: 3000,
      max_restarts: 10,
      autorestart: true,
      watch: false,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      error_file: "/var/log/tradereplay/kafka-service-error.log",
      out_file: "/var/log/tradereplay/kafka-service-out.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "tradereplay-chart-service",
      script: "tsx",
      args: "src/index.ts",
      cwd: "/opt/tradereplay/services/chart-service",
      instances: 1,
      exec_mode: "fork",
      env_file: "/opt/tradereplay/.env",
      env: {
        NODE_ENV: "production",
        APP_ENV: "production",
        PORT: process.env.CHART_SERVICE_PORT || "4010",
        BACKEND_URL: process.env.BACKEND_URL || "http://127.0.0.1:4000",
        REDIS_URL: process.env.REDIS_URL_LOCAL || "redis://127.0.0.1:6379",
        KAFKA_BROKERS: process.env.KAFKA_BROKER_LOCAL || "127.0.0.1:9092",
      },
      max_memory_restart: "300M",
      restart_delay: 3000,
      max_restarts: 10,
      autorestart: true,
      watch: false,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      error_file: "/var/log/tradereplay/chart-service-error.log",
      out_file: "/var/log/tradereplay/chart-service-out.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "tradereplay-asset-service",
      script: "tsx",
      args: "src/assetService.ts",
      cwd: "/opt/tradereplay/backend",
      instances: 1,
      exec_mode: "fork",
      env_file: "/opt/tradereplay/.env",
      env: {
        NODE_ENV: "production",
      },
      max_memory_restart: "400M",
      restart_delay: 10000,
      max_restarts: 20,
      autorestart: true,
      watch: false,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      error_file: "/var/log/tradereplay/asset-service-error.log",
      out_file: "/var/log/tradereplay/asset-service-out.log",
      merge_logs: true,
      time: true,
    },
  ],
};
