module.exports = {
  apps: [
    {
      name: "tradereplay-backend",
      script: "tsx",
      args: "src/server.ts",
      cwd: "/opt/tradereplay/backend",
      instances: 1,
      exec_mode: "fork",
      env_file: "/opt/tradereplay/.env",
      env: {
        NODE_ENV: "production",
      },
      max_memory_restart: "450M",
      node_args: "--max-old-space-size=400",
      restart_delay: 3000,
      max_restarts: 10,
      autorestart: true,
      watch: false,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      error_file: "/var/log/tradereplay/error.log",
      out_file: "/var/log/tradereplay/out.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "tradereplay-worker",
      script: "tsx",
      args: "src/worker.ts",
      cwd: "/opt/tradereplay/backend",
      instances: 1,
      exec_mode: "fork",
      env_file: "/opt/tradereplay/.env",
      env: {
        NODE_ENV: "production",
      },
      max_memory_restart: "200M",
      restart_delay: 3000,
      max_restarts: 10,
      autorestart: true,
      watch: false,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      error_file: "/var/log/tradereplay/worker-error.log",
      out_file: "/var/log/tradereplay/worker-out.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "tradereplay-logo-service",
      script: "tsx",
      args: "src/index.ts",
      cwd: "/opt/tradereplay/services/logo-service",
      instances: 1,
      exec_mode: "fork",
      env_file: "/opt/tradereplay/.env",
      env: {
        NODE_ENV: "production",
      },
      max_memory_restart: "150M",
      restart_delay: 3000,
      max_restarts: 10,
      autorestart: true,
      watch: false,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      error_file: "/var/log/tradereplay/logo-service-error.log",
      out_file: "/var/log/tradereplay/logo-service-out.log",
      merge_logs: true,
      time: true,
    },
  ],
};