module.exports = {
  apps: [
    {
      name: "tradereplay-backend",
      script: "tsx",
      args: "src/server.ts",
      cwd: "/opt/tradereplay/backend",
      instances: 1,
      exec_mode: "fork",
      env_file: "/opt/tradereplay/.env",
      env: {
        NODE_ENV: "production",
      },
      max_memory_restart: "300M",
      restart_delay: 3000,
      max_restarts: 10,
      autorestart: true,
      watch: false,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      error_file: "/var/log/tradereplay/error.log",
      out_file: "/var/log/tradereplay/out.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "tradereplay-worker",
      script: "tsx",
      args: "src/worker.ts",
      cwd: "/opt/tradereplay/backend",
      instances: Number(process.env.WORKER_INSTANCES || 1),
      exec_mode: "fork",
      env_file: "/opt/tradereplay/.env",
      env: {
        NODE_ENV: "production",
      },
      max_memory_restart: "300M",
      restart_delay: 3000,
      max_restarts: 10,
      autorestart: true,
      watch: false,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      error_file: "/var/log/tradereplay/worker-error.log",
      out_file: "/var/log/tradereplay/worker-out.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "tradereplay-logo-service",
      script: "tsx",
      args: "src/index.ts",
      cwd: "/opt/tradereplay/services/logo-service",
      instances: Number(process.env.LOGO_SERVICE_INSTANCES || 1),
      exec_mode: "fork",
      env_file: "/opt/tradereplay/.env",
      env: {
        NODE_ENV: "production",
      },
      max_memory_restart: "300M",
      restart_delay: 3000,
      max_restarts: 10,
      autorestart: true,
      watch: false,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      error_file: "/var/log/tradereplay/logo-service-error.log",
      out_file: "/var/log/tradereplay/logo-service-out.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "tradereplay-kafka-service",
      script: "tsx",
      args: "src/kafkaService.ts",
      cwd: "/opt/tradereplay/backend",
      instances: 1,
      exec_mode: "fork",
      env_file: "/opt/tradereplay/.env",
      env: {
        NODE_ENV: "production",
      },
      max_memory_restart: "300M",
      restart_delay: 3000,
      max_restarts: 10,
      autorestart: true,
      watch: false,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      error_file: "/var/log/tradereplay/kafka-service-error.log",
      out_file: "/var/log/tradereplay/kafka-service-out.log",
      merge_logs: true,
      time: true,
    },
    // global-expansion: REMOVED from always-on processes.
    // Run manually when needed: tsx src/jobs/globalInfiniteExpansionLoop.ts

    // ─── Microservices ─────────────────────────────────────
    {
      name: "tradereplay-asset-service",
      script: "tsx",
      args: "src/index.ts",
      cwd: "/opt/tradereplay/services/asset-service",
      instances: 1,
      exec_mode: "fork",
      env_file: "/opt/tradereplay/.env",
      env: { NODE_ENV: "production", PORT: 3002 },
      max_memory_restart: "200M",
      restart_delay: 3000,
      max_restarts: 10,
      autorestart: true,
      watch: false,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      error_file: "/var/log/tradereplay/asset-service-error.log",
      out_file: "/var/log/tradereplay/asset-service-out.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "tradereplay-screener-service",
      script: "tsx",
      args: "src/index.ts",
      cwd: "/opt/tradereplay/services/screener-service",
      instances: 1,
      exec_mode: "fork",
      env_file: "/opt/tradereplay/.env",
      env: { NODE_ENV: "production", PORT: 3004 },
      max_memory_restart: "200M",
      restart_delay: 3000,
      max_restarts: 10,
      autorestart: true,
      watch: false,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      error_file: "/var/log/tradereplay/screener-service-error.log",
      out_file: "/var/log/tradereplay/screener-service-out.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "tradereplay-alert-service",
      script: "tsx",
      args: "src/index.ts",
      cwd: "/opt/tradereplay/services/alert-service",
      instances: 1,
      exec_mode: "fork",
      env_file: "/opt/tradereplay/.env",
      env: { NODE_ENV: "production", PORT: 3005 },
      max_memory_restart: "150M",
      restart_delay: 3000,
      max_restarts: 10,
      autorestart: true,
      watch: false,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      error_file: "/var/log/tradereplay/alert-service-error.log",
      out_file: "/var/log/tradereplay/alert-service-out.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "tradereplay-portfolio-service",
      script: "tsx",
      args: "src/index.ts",
      cwd: "/opt/tradereplay/services/portfolio-service",
      instances: 1,
      exec_mode: "fork",
      env_file: "/opt/tradereplay/.env",
      env: { NODE_ENV: "production", PORT: 3006 },
      max_memory_restart: "150M",
      restart_delay: 3000,
      max_restarts: 10,
      autorestart: true,
      watch: false,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      error_file: "/var/log/tradereplay/portfolio-service-error.log",
      out_file: "/var/log/tradereplay/portfolio-service-out.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "tradereplay-simulation-service",
      script: "tsx",
      args: "src/index.ts",
      cwd: "/opt/tradereplay/services/simulation-service",
      instances: 1,
      exec_mode: "fork",
      env_file: "/opt/tradereplay/.env",
      env: { NODE_ENV: "production", PORT: 3007 },
      max_memory_restart: "200M",
      restart_delay: 3000,
      max_restarts: 10,
      autorestart: true,
      watch: false,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      error_file: "/var/log/tradereplay/simulation-service-error.log",
      out_file: "/var/log/tradereplay/simulation-service-out.log",
      merge_logs: true,
      time: true,
    },
    {
      name: "tradereplay-datafeed-service",
      script: "tsx",
      args: "src/index.ts",
      cwd: "/opt/tradereplay/services/datafeed-service",
      instances: 1,
      exec_mode: "fork",
      env_file: "/opt/tradereplay/.env",
      env: { NODE_ENV: "production", PORT: 3008 },
      max_memory_restart: "200M",
      restart_delay: 3000,
      max_restarts: 10,
      autorestart: true,
      watch: false,
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      error_file: "/var/log/tradereplay/datafeed-service-error.log",
      out_file: "/var/log/tradereplay/datafeed-service-out.log",
      merge_logs: true,
      time: true,
    },
  ],
};
