import type { AssetCategory, AssetSearchFilterOption, AssetSearchFiltersResponse } from "@/lib/assetSearch";

const option = (value: string, label: string): AssetSearchFilterOption => ({ value, label });
const s = (label: string): AssetSearchFilterOption =>
  option(label.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, ""), label);

// ── Countries ─────────────────────────────────────────────────────────────────
export const PREDEFINED_COUNTRIES: AssetSearchFilterOption[] = [
  option("all", "All Countries"),
  option("US", "United States"),
  option("IN", "India"),
  option("GB", "United Kingdom"),
  option("DE", "Germany"),
  option("FR", "France"),
  option("JP", "Japan"),
  option("CN", "China"),
  option("CA", "Canada"),
  option("AU", "Australia"),
  option("SG", "Singapore"),
  option("CH", "Switzerland"),
  option("AE", "United Arab Emirates"),
  option("BR", "Brazil"),
  option("MX", "Mexico"),
  option("ZA", "South Africa"),
  option("KR", "South Korea"),
  option("HK", "Hong Kong"),
  option("ES", "Spain"),
  option("IT", "Italy"),
  option("NL", "Netherlands"),
  option("SE", "Sweden"),
  option("NO", "Norway"),
  option("DK", "Denmark"),
  option("FI", "Finland"),
  option("BE", "Belgium"),
  option("AT", "Austria"),
  option("IE", "Ireland"),
  option("PT", "Portugal"),
  option("PL", "Poland"),
  option("CZ", "Czechia"),
  option("HU", "Hungary"),
  option("RO", "Romania"),
  option("GR", "Greece"),
  option("TR", "Turkey"),
  option("IL", "Israel"),
  option("SA", "Saudi Arabia"),
  option("QA", "Qatar"),
  option("KW", "Kuwait"),
  option("EG", "Egypt"),
  option("NG", "Nigeria"),
  option("KE", "Kenya"),
  option("MA", "Morocco"),
  option("AR", "Argentina"),
  option("CL", "Chile"),
  option("CO", "Colombia"),
  option("PE", "Peru"),
  option("NZ", "New Zealand"),
  option("TH", "Thailand"),
  option("MY", "Malaysia"),
  option("ID", "Indonesia"),
  option("PH", "Philippines"),
  option("VN", "Vietnam"),
  option("PK", "Pakistan"),
  option("BD", "Bangladesh"),
  option("LK", "Sri Lanka"),
  option("TW", "Taiwan"),
  option("RU", "Russia"),
  option("UA", "Ukraine"),
  option("KZ", "Kazakhstan"),
  option("LU", "Luxembourg"),
  option("IS", "Iceland"),
  option("EE", "Estonia"),
  option("LV", "Latvia"),
  option("LT", "Lithuania"),
];

// ── Stock Filters ─────────────────────────────────────────────────────────────
export const STOCK_TYPES: AssetSearchFilterOption[] = [
  option("stock", "Stocks"),
];

export const STOCK_SECTORS: AssetSearchFilterOption[] = [
  option("all", "All sectors"),
  option("commercial_services", "Commercial Services"),
  option("communications", "Communications"),
  option("consumer_durables", "Consumer Durables"),
  option("consumer_non_durables", "Consumer Non-Durables"),
  option("consumer_services", "Consumer Services"),
  option("distribution_services", "Distribution Services"),
  option("electronic_technology", "Electronic Technology"),
  option("energy_minerals", "Energy Minerals"),
  option("finance", "Finance"),
  option("government_sector", "Government sector"),
  option("health_services", "Health Services"),
  option("health_technology", "Health Technology"),
  option("industrial_services", "Industrial Services"),
  option("miscellaneous", "Miscellaneous"),
  option("non_energy_minerals", "Non-Energy Minerals"),
  option("process_industries", "Process Industries"),
  option("producer_manufacturing", "Producer Manufacturing"),
  option("retail_trade", "Retail Trade"),
  option("technology_services", "Technology Services"),
  option("transportation", "Transportation"),
  option("utilities", "Utilities"),
];

// ── Funds ─────────────────────────────────────────────────────────────────────
export const FUND_TYPES: AssetSearchFilterOption[] = [
  option("etf", "ETFs"),
];

// ── Futures ───────────────────────────────────────────────────────────────────
export const FUTURES_CATEGORIES: AssetSearchFilterOption[] = [
  option("all", "All categories"),
  option("single_stock", "Single stock"),
  option("world_indices", "World indices"),
  option("currencies", "Currencies"),
  option("interest_rates", "Interest rates"),
  option("energy", "Energy"),
  option("agriculture", "Agriculture"),
  option("metals", "Metals"),
  option("weather", "Weather"),
  option("building_materials", "Building materials"),
  option("chemicals", "Chemicals"),
];

// ── Bonds ─────────────────────────────────────────────────────────────────────
export const BOND_TYPES: AssetSearchFilterOption[] = [
  option("stock", "Bonds"),
];

// ── Forex Sources ─────────────────────────────────────────────────────────────
export const FOREX_SOURCES: AssetSearchFilterOption[] = [
  option("all", "All sources"),
  s("ActivTrades"),
  s("B2PRIME"),
  s("BlackBull Markets"),
  s("Blueberry"),
  s("Capital.com"),
  s("CFI"),
  s("City Index"),
  s("CMC Markets"),
  s("CXM"),
  s("easyMarkets"),
  s("Eightcap"),
  s("Errante"),
  s("EsaFX"),
  s("FOREX.com"),
  s("FP Markets"),
  s("Fusion Markets"),
  s("FXCM"),
  s("FXOpen"),
  s("FxPro"),
  s("GBE brokers"),
  s("GO Markets"),
  s("iBroker"),
  s("IC Markets"),
  s("ICE"),
  s("IG"),
  s("Interactive Brokers"),
  s("JFX"),
  s("MATSUI"),
  s("OANDA"),
  s("Opofinance"),
  s("Osmanli FX"),
  s("Pepperstone"),
  s("Phillip Nova"),
  s("Purple Trading"),
  s("Saxo"),
  s("Skilling"),
  s("Spreadex"),
  s("Swissquote"),
  s("tastyfx"),
  s("ThinkMarkets"),
  s("Tickmill"),
  s("Trade Nation"),
  s("Trive"),
  s("Vantage"),
  s("Velocity Trade"),
  s("WH SelfInvest"),
];

// ── Crypto Sources ────────────────────────────────────────────────────────────
export const CRYPTO_SOURCES: AssetSearchFilterOption[] = [
  option("all", "All sources"),
  s("ActivTrades"),
  s("Aerodrome (Base)"),
  s("Aerodrome SlipStream (Base)"),
  s("Antarctic"),
  s("B2PRIME"),
  s("BaseSwap (Base)"),
  s("BCHAIN (Nasdaq Data Link)"),
  s("Binance"),
  s("Binance.US"),
  s("BingX"),
  s("Biswap v2 (BNB chain)"),
  s("Bitazza"),
  s("Bitfinex"),
  s("bitFlyer"),
  s("Bitget"),
  s("Bithumb"),
  s("Bitkub"),
  s("BitMart"),
  s("BitMEX"),
  s("Bitrue"),
  s("Bitso"),
  s("Bitstamp"),
  s("Bittrex"),
  s("Bitunix"),
  s("Bitvavo"),
  s("BlackBull Markets"),
  s("Blackhole v3 (Avalanche)"),
  s("BloFin"),
  s("Blueberry"),
  s("Bluefin (Sui)"),
  s("Brave New Coin"),
  s("BTCC"),
  s("BTSE"),
  s("Bybit"),
  s("BYDFi"),
  s("Camelot v2 (Arbitrum)"),
  s("Camelot v3 (Arbitrum)"),
  s("Capital.com"),
  s("CFI"),
  s("Cetus (Sui)"),
  s("City Index"),
  s("CMC Markets"),
  s("Coin Metrics"),
  s("Coinbase"),
  s("CoinDesk Indices"),
  s("CoinEx"),
  s("CoinW"),
  s("Crypto.com"),
  s("Curve (Arbitrum)"),
  s("Curve (Ethereum)"),
  s("CXM"),
  s("DeDust.io (TON)"),
  s("DefiLlama"),
  s("Delta Exchange"),
  s("Delta Exchange India"),
  s("Deribit"),
  s("Eightcap"),
  s("Errante"),
  s("EsaFX"),
  s("FOREX.com"),
  s("FP Markets"),
  s("Fusion Markets"),
  s("FXCM"),
  s("FXOpen"),
  s("FxPro"),
  s("GBE brokers"),
  s("Gate"),
  s("Gemini"),
  s("Glassnode"),
  s("GO Markets"),
  s("HTX"),
  s("HoneySwap v2 (Gnosis)"),
  s("ICE"),
  s("IG"),
  s("Interactive Brokers"),
  s("iBroker"),
  s("IC Markets"),
  s("JFX"),
  s("Katana (Ronin)"),
  s("Katana v3 (Ronin)"),
  s("KCEX"),
  s("Kraken"),
  s("KuCoin"),
  s("LBank"),
  s("LFJ V2.2 (Avalanche)"),
  s("LunarCrush"),
  s("MEXC"),
  s("MM Finance (Cronos)"),
  s("MATSUI"),
  s("Meteora DLMM (Solana)"),
  s("Meteora DYN (Solana)"),
  s("OKX"),
  s("OANDA"),
  s("Opofinance"),
  s("Orca (Solana)"),
  s("Osmosis"),
  s("Osmanli FX"),
  s("PancakeSwap v2 (BNB chain)"),
  s("PancakeSwap v3 (Arbitrum)"),
  s("PancakeSwap v3 (Base)"),
  s("PancakeSwap v3 (BNB chain)"),
  s("PancakeSwap v3 (Ethereum)"),
  s("PancakeSwap v3 (zkSync)"),
  s("Pangolin v2 (Avalanche)"),
  s("Pepperstone"),
  s("Phemex"),
  s("Phillip Nova"),
  s("Pionex"),
  s("Poloniex"),
  s("PulseX (Pulsechain)"),
  s("PulseX v2 (Pulsechain)"),
  s("Purple Trading"),
  s("Pyth"),
  s("QuickSwap v2 (Polygon)"),
  s("QuickSwap v3 (Polygon)"),
  s("QuickSwap v3 (Polygon zkEVM)"),
  s("Ramses v2 (Arbitrum)"),
  s("Raydium (Solana)"),
  s("Raydium CLMM (Solana)"),
  s("Raydium CPMM (Solana)"),
  s("Saxo"),
  s("Skilling"),
  s("Spreadex"),
  s("SpookySwap v2 (Fantom)"),
  s("STON.fi (TON)"),
  s("STON.fi v2 (TON)"),
  s("SunSwap v2 (TRON)"),
  s("Swissquote"),
  s("SushiSwap v2 (Ethereum)"),
  s("SushiSwap v2 (Polygon)"),
  s("SyncSwap (zkSync)"),
  s("SyncSwap v2 (zkSync)"),
  s("tastyfx"),
  s("ThinkMarkets"),
  s("Tickmill"),
  s("Toobit"),
  s("Trade Nation"),
  s("Trader Joe v2 (Avalanche)"),
  s("Trive"),
  s("Turbos Finance (Sui)"),
  s("Uniswap v2 (Base)"),
  s("Uniswap v2 (Ethereum)"),
  s("Uniswap v2 (Unichain)"),
  s("Uniswap v3 (Arbitrum)"),
  s("Uniswap v3 (Avalanche)"),
  s("Uniswap v3 (Base)"),
  s("Uniswap v3 (Ethereum)"),
  s("Uniswap v3 (Optimism)"),
  s("Uniswap v3 (Polygon)"),
  s("UpBit"),
  s("Vantage"),
  s("Velocity Trade"),
  s("Velodrome (Optimism)"),
  s("Velodrome SlipStream (Optimism)"),
  s("Velodrome v2 (Optimism)"),
  s("Volmex"),
  s("VVS Finance (Cronos)"),
  s("VVS v3 (Cronos)"),
  s("Webull Pay"),
  s("WEEX"),
  s("WhiteBIT"),
  s("WH SelfInvest"),
  s("WOO X"),
  s("xExchange"),
  s("XT.com"),
  s("zkSwap (zkSync)"),
  s("Zoomex"),
];

export const CRYPTO_TYPES: AssetSearchFilterOption[] = [
  option("crypto", "Cryptocurrencies"),
];

export const CRYPTO_EXCHANGE_TYPES: AssetSearchFilterOption[] = [
  option("all", "All exchange types"),
  option("cex", "CEX"),
  option("dex", "DEX"),
];

// ── Indices Sources (countries + providers) ───────────────────────────────────
export const INDICES_SOURCES: AssetSearchFilterOption[] = [
  option("all", "All sources"),
  // Countries
  option("us", "USA"),
  option("ca", "Canada"),
  option("at", "Austria"),
  option("be", "Belgium"),
  option("bg", "Bulgaria"),
  option("hr", "Croatia"),
  option("cy", "Cyprus"),
  option("cz", "Czech Republic"),
  option("dk", "Denmark"),
  option("ee", "Estonia"),
  option("eu", "European Union"),
  option("fi", "Finland"),
  option("fr", "France"),
  option("de", "Germany"),
  option("gr", "Greece"),
  option("hu", "Hungary"),
  option("is", "Iceland"),
  option("ie", "Ireland"),
  option("it", "Italy"),
  option("lv", "Latvia"),
  option("lt", "Lithuania"),
  option("lu", "Luxembourg"),
  option("nl", "Netherlands"),
  option("no", "Norway"),
  option("pl", "Poland"),
  option("pt", "Portugal"),
  option("ro", "Romania"),
  option("ru", "Russia"),
  option("rs", "Serbia"),
  option("sk", "Slovakia"),
  option("si", "Slovenia"),
  option("es", "Spain"),
  option("se", "Sweden"),
  option("ch", "Switzerland"),
  option("tr", "Turkey"),
  option("gb", "United Kingdom"),
  option("bh", "Bahrain"),
  option("eg", "Egypt"),
  option("il", "Israel"),
  option("ke", "Kenya"),
  option("kw", "Kuwait"),
  option("ma", "Morocco"),
  option("ng", "Nigeria"),
  option("qa", "Qatar"),
  option("sa", "Saudi Arabia"),
  option("za", "South Africa"),
  option("tn", "Tunisia"),
  option("ae", "United Arab Emirates"),
  option("ar", "Argentina"),
  option("br", "Brazil"),
  option("cl", "Chile"),
  option("co", "Colombia"),
  option("mx", "Mexico"),
  option("pe", "Peru"),
  option("ve", "Venezuela"),
  option("au", "Australia"),
  option("bd", "Bangladesh"),
  option("hk", "Hong Kong, China"),
  option("in", "India"),
  option("id", "Indonesia"),
  option("jp", "Japan"),
  option("cn", "Mainland China"),
  option("my", "Malaysia"),
  option("nz", "New Zealand"),
  option("pk", "Pakistan"),
  option("ph", "Philippines"),
  option("sg", "Singapore"),
  option("kr", "South Korea"),
  option("lk", "Sri Lanka"),
  option("tw", "Taiwan, China"),
  option("th", "Thailand"),
  option("vn", "Vietnam"),
  // Providers
  s("ActivTrades"),
  s("B2PRIME"),
  s("BlackBull Markets"),
  s("Blueberry"),
  s("Capital.com"),
  s("CFI"),
  s("City Index"),
  s("CMC Markets"),
  s("CXM"),
  s("easyMarkets"),
  s("Eightcap"),
  s("Errante"),
  s("EsaFX"),
  s("FOREX.com"),
  s("FP Markets"),
  s("Fusion Markets"),
  s("FXCM"),
  s("FXOpen"),
  s("FxPro"),
  s("GBE brokers"),
  s("GO Markets"),
  s("iBroker"),
  s("IC Markets"),
  s("ICE"),
  s("IG"),
  s("Interactive Brokers"),
  s("JFX"),
  s("MATSUI"),
  s("OANDA"),
  s("Opofinance"),
  s("Osmanli FX"),
  s("Pepperstone"),
  s("Phillip Nova"),
  s("Purple Trading"),
  s("Saxo"),
  s("Skilling"),
  s("Spreadex"),
  s("Swissquote"),
  s("tastyfx"),
  s("ThinkMarkets"),
  s("Tickmill"),
  s("Trade Nation"),
  s("Trive"),
  s("Vantage"),
  s("Velocity Trade"),
  s("WH SelfInvest"),
];

// ── Economy ───────────────────────────────────────────────────────────────────
export const ECONOMY_SOURCES: AssetSearchFilterOption[] = [
  option("all", "All sources"),
  option("world_bank", "World Bank"),
  option("eurostat", "EUROSTAT"),
  option("akamai", "AKAMAI"),
  option("transparency_international", "Transparency International"),
  option("oecd", "Organisation for Economic Co-operation and Development"),
  option("wef", "World Economic Forum"),
  option("wageindicator", "WageIndicator Foundation"),
  option("bls", "Bureau of Labour Statistics"),
  option("fed", "Federal Reserve"),
  option("sipri", "Stockholm International Peace Research Institute"),
  option("iep", "Institute for Economics and Peace"),
  option("bea", "Bureau of Economics Analysis"),
  option("world_gold_council", "World Gold Council"),
  option("census", "Census Bureau"),
  option("bceao", "Central Bank of West African States (BCEAO)"),
  option("imf", "International Monetary Fund (IMF)"),
  option("eia", "U.S. Energy Information Administration"),
  option("statscan", "Statistics Canada"),
  option("ons", "Office for National Statistics"),
  option("ssb", "Statistics Norway"),
];

export const ECONOMY_CATEGORIES: AssetSearchFilterOption[] = [
  option("all", "All categories"),
  option("gdp", "GDP"),
  option("labor", "Labor"),
  option("prices", "Prices"),
  option("health", "Health"),
  option("money", "Money"),
  option("trade", "Trade"),
  option("government", "Government"),
  option("business", "Business"),
  option("consumer", "Consumer"),
  option("housing", "Housing"),
  option("taxes", "Taxes"),
];

// ── Helper ────────────────────────────────────────────────────────────────────
function emptyFilters(sourceUiType: "modal" | "dropdown" = "modal"): AssetSearchFiltersResponse {
  return {
    activeFilters: [],
    countries: [],
    types: [],
    sectors: [],
    sources: [],
    exchangeTypes: [],
    futureCategories: [],
    economyCategories: [],
    expiries: [],
    strikes: [],
    underlyingAssets: [],
    sourceUiType,
  };
}

// ── Static Filter Resolver ────────────────────────────────────────────────────
export function getStaticFilters(category?: "all" | AssetCategory): AssetSearchFiltersResponse {
  const resolved = category ?? "all";

  if (resolved === "all") return emptyFilters("modal");

  if (resolved === "stocks") {
    return {
      ...emptyFilters("modal"),
      activeFilters: ["country"],
      countries: PREDEFINED_COUNTRIES,
    };
  }

  if (resolved === "funds") {
    return {
      ...emptyFilters("modal"),
      activeFilters: ["country"],
      countries: PREDEFINED_COUNTRIES,
    };
  }

  if (resolved === "futures") {
    return {
      ...emptyFilters("modal"),
      activeFilters: ["futureCategory", "country"],
      countries: PREDEFINED_COUNTRIES,
      futureCategories: FUTURES_CATEGORIES,
    };
  }

  if (resolved === "forex") {
    return {
      ...emptyFilters("modal"),
      activeFilters: ["source"],
      sources: FOREX_SOURCES,
      sourceUiType: "modal",
    };
  }

  if (resolved === "crypto") {
    return {
      ...emptyFilters("modal"),
      activeFilters: ["source"],
      sources: CRYPTO_SOURCES,
      sourceUiType: "modal",
    };
  }

  if (resolved === "indices") {
    return {
      ...emptyFilters("modal"),
      activeFilters: ["source"],
      sources: INDICES_SOURCES,
      sourceUiType: "modal",
    };
  }

  if (resolved === "bonds") {
    return {
      ...emptyFilters("modal"),
      activeFilters: ["country"],
      countries: PREDEFINED_COUNTRIES,
    };
  }

  if (resolved === "economy") {
    return {
      ...emptyFilters("dropdown"),
      activeFilters: ["country", "source", "economyCategory"],
      countries: PREDEFINED_COUNTRIES,
      sources: ECONOMY_SOURCES,
      economyCategories: ECONOMY_CATEGORIES,
      sourceUiType: "dropdown",
    };
  }

  if (resolved === "options") {
    return {
      ...emptyFilters("modal"),
      activeFilters: ["country", "expiry", "underlyingAsset"],
      countries: PREDEFINED_COUNTRIES,
      types: [
        option("derivative", "Options"),
      ],
      expiries: [
        option("all", "All Expiries"),
        option("weekly", "Weekly"),
        option("monthly", "Monthly"),
        option("quarterly", "Quarterly"),
        option("2026-06", "Jun 2026"),
        option("2026-07", "Jul 2026"),
        option("2026-09", "Sep 2026"),
        option("2026-12", "Dec 2026"),
        option("2027-03", "Mar 2027"),
        option("2027-06", "Jun 2027"),
      ],
      underlyingAssets: [
        option("all", "All Underlying"),
        option("AAPL", "Apple Inc."),
        option("MSFT", "Microsoft Corp."),
        option("TSLA", "Tesla Inc."),
        option("AMZN", "Amazon.com"),
        option("GOOGL", "Alphabet Inc."),
        option("META", "Meta Platforms"),
        option("NVDA", "NVIDIA Corp."),
        option("SPY", "SPDR S&P 500 ETF"),
        option("QQQ", "Invesco QQQ Trust"),
        option("NIFTY", "NIFTY 50"),
        option("BANKNIFTY", "Bank NIFTY"),
        option("BTC", "Bitcoin"),
        option("ETH", "Ethereum"),
      ],
    };
  }

  return emptyFilters("modal");
}
