export const POPULAR_COUNTRIES = [
  { flag: "🌐", name: "Entire world", value: "WORLD" },
  { flag: "🇮🇳", name: "India", value: "IN" },
  { flag: "🇺🇸", name: "USA", value: "US" },
  { flag: "🇩🇪", name: "Germany", value: "DE" },
  { flag: "🇯🇵", name: "Japan", value: "JP" },
  { flag: "🇨🇦", name: "Canada", value: "CA" },
  { flag: "🇭🇰", name: "Hong Kong, China", value: "HK" },
  { flag: "🇬🇧", name: "United Kingdom", value: "GB" },
];

export const ALL_COUNTRIES = [
  { flag: "🇦🇷", name: "Argentina", value: "AR" },
  { flag: "🇦🇺", name: "Australia", value: "AU" },
  { flag: "🇦🇹", name: "Austria", value: "AT" },
  { flag: "🇧🇭", name: "Bahrain", value: "BH" },
  { flag: "🇧🇩", name: "Bangladesh", value: "BD" },
  { flag: "🇧🇪", name: "Belgium", value: "BE" },
  { flag: "🇧🇷", name: "Brazil", value: "BR" },
  { flag: "🇧🇬", name: "Bulgaria", value: "BG" },
  { flag: "🇨🇦", name: "Canada", value: "CA" },
  { flag: "🇨🇱", name: "Chile", value: "CL" },
  { flag: "🇨🇳", name: "Mainland China", value: "CN" },
  { flag: "🇨🇴", name: "Colombia", value: "CO" },
  { flag: "🇭🇷", name: "Croatia", value: "HR" },
  { flag: "🇨🇾", name: "Cyprus", value: "CY" },
  { flag: "🇨🇿", name: "Czech Republic", value: "CZ" },
  { flag: "🇩🇰", name: "Denmark", value: "DK" },
  { flag: "🇪🇬", name: "Egypt", value: "EG" },
  { flag: "🇪🇪", name: "Estonia", value: "EE" },
  { flag: "🇫🇮", name: "Finland", value: "FI" },
  { flag: "🇫🇷", name: "France", value: "FR" },
  { flag: "🇩🇪", name: "Germany", value: "DE" },
  { flag: "🇬🇷", name: "Greece", value: "GR" },
  { flag: "🇭🇰", name: "Hong Kong, China", value: "HK" },
  { flag: "🇭🇺", name: "Hungary", value: "HU" },
  { flag: "🇮🇸", name: "Iceland", value: "IS" },
  { flag: "🇮🇳", name: "India", value: "IN" },
  { flag: "🇮🇩", name: "Indonesia", value: "ID" },
  { flag: "🇮🇪", name: "Ireland", value: "IE" },
  { flag: "🇮🇱", name: "Israel", value: "IL" },
  { flag: "🇮🇹", name: "Italy", value: "IT" },
  { flag: "🇯🇵", name: "Japan", value: "JP" },
  { flag: "🇰🇪", name: "Kenya", value: "KE" },
  { flag: "🇰🇼", name: "Kuwait", value: "KW" },
  { flag: "🇱🇻", name: "Latvia", value: "LV" },
  { flag: "🇱🇹", name: "Lithuania", value: "LT" },
  { flag: "🇱🇺", name: "Luxembourg", value: "LU" },
  { flag: "🇲🇾", name: "Malaysia", value: "MY" },
  { flag: "🇲🇽", name: "Mexico", value: "MX" },
  { flag: "🇲🇦", name: "Morocco", value: "MA" },
  { flag: "🇳🇱", name: "Netherlands", value: "NL" },
  { flag: "🇳🇿", name: "New Zealand", value: "NZ" },
  { flag: "🇳🇬", name: "Nigeria", value: "NG" },
  { flag: "🇳🇴", name: "Norway", value: "NO" },
  { flag: "🇵🇰", name: "Pakistan", value: "PK" },
  { flag: "🇵🇪", name: "Peru", value: "PE" },
  { flag: "🇵🇭", name: "Philippines", value: "PH" },
  { flag: "🇵🇱", name: "Poland", value: "PL" },
  { flag: "🇵🇹", name: "Portugal", value: "PT" },
  { flag: "🇶🇦", name: "Qatar", value: "QA" },
  { flag: "🇷🇴", name: "Romania", value: "RO" },
  { flag: "🇷🇺", name: "Russia", value: "RU" },
  { flag: "🇸🇦", name: "Saudi Arabia", value: "SA" },
  { flag: "🇷🇸", name: "Serbia", value: "RS" },
  { flag: "🇸🇬", name: "Singapore", value: "SG" },
  { flag: "🇸🇰", name: "Slovakia", value: "SK" },
  { flag: "🇸🇮", name: "Slovenia", value: "SI" },
  { flag: "🇿🇦", name: "South Africa", value: "ZA" },
  { flag: "🇰🇷", name: "South Korea", value: "KR" },
  { flag: "🇪🇸", name: "Spain", value: "ES" },
  { flag: "🇱🇰", name: "Sri Lanka", value: "LK" },
  { flag: "🇸🇪", name: "Sweden", value: "SE" },
  { flag: "🇨🇭", name: "Switzerland", value: "CH" },
  { flag: "🇹🇼", name: "Taiwan, China", value: "TW" },
  { flag: "🇹🇭", name: "Thailand", value: "TH" },
  { flag: "🇹🇳", name: "Tunisia", value: "TN" },
  { flag: "🇹🇷", name: "Turkey", value: "TR" },
  { flag: "🇦🇪", name: "UAE", value: "AE" },
  { flag: "🇬🇧", name: "United Kingdom", value: "GB" },
  { flag: "🇺🇸", name: "USA", value: "US" },
  { flag: "🇻🇪", name: "Venezuela", value: "VE" },
  { flag: "🇻🇳", name: "Vietnam", value: "VN" },
  { flag: "🌐", name: "Other", value: "OTHER" },
];

export interface IndexGroupDef {
  flag: string;
  region: string;
  indices: Array<{ ticker: string; name: string }>;
}

export const INDEX_GROUPS: IndexGroupDef[] = [
  { flag: "🇺🇸", region: "US INDICES", indices: [
    { ticker: "SPX", name: "S&P 500" },
    { ticker: "IXIC", name: "US Composite Index" },
    { ticker: "DJI", name: "Dow Jones Industrial Average" },
    { ticker: "VIX", name: "CBOE Volatility Index" },
    { ticker: "RUT", name: "US Small Cap 2000" },
    { ticker: "RUA", name: "US Small Cap 3000" },
    { ticker: "RUI", name: "US Small Cap 1000" },
    { ticker: "NYA", name: "NYSE Composite" },
    { ticker: "XAX", name: "NYSE American Composite" },
  ]},
  { flag: "🇨🇦", region: "CANADA", indices: [{ ticker: "TSX", name: "S&P/TSX Composite" }] },
  { flag: "🇬🇧", region: "UK", indices: [{ ticker: "UKX", name: "UK 100" }] },
  { flag: "🇩🇪", region: "GERMANY", indices: [{ ticker: "DAX", name: "German Index (DAX)" }] },
  { flag: "🇫🇷", region: "FRANCE", indices: [{ ticker: "CAC40", name: "CAC 40" }] },
  { flag: "🇪🇺", region: "EUROPE", indices: [
    { ticker: "SX5E", name: "STOXX 50" },
    { ticker: "SXXP", name: "STOXX 600" },
  ]},
  { flag: "🇳🇱", region: "NETHERLANDS", indices: [{ ticker: "AEX", name: "AEX Index" }] },
  { flag: "🇧🇪", region: "BELGIUM", indices: [{ ticker: "BEL20", name: "BEL 20" }] },
  { flag: "🇪🇸", region: "SPAIN", indices: [{ ticker: "IBEX35", name: "IBEX 35" }] },
  { flag: "🇨🇭", region: "SWITZERLAND", indices: [{ ticker: "SMI", name: "Swiss Market Index" }] },
  { flag: "🇫🇮", region: "FINLAND", indices: [{ ticker: "OMXH25", name: "OMX Helsinki 25" }] },
  { flag: "🇸🇪", region: "SWEDEN", indices: [{ ticker: "OMXS30", name: "OMX Stockholm 30" }] },
  { flag: "🇩🇰", region: "DENMARK", indices: [{ ticker: "OMXC25", name: "OMX Copenhagen 25" }] },
  { flag: "🇮🇹", region: "ITALY", indices: [{ ticker: "FTMIB", name: "Milano Italia Borsa" }] },
  { flag: "🇵🇱", region: "POLAND", indices: [{ ticker: "WIG20", name: "Poland Index" }] },
  { flag: "🇷🇴", region: "ROMANIA", indices: [{ ticker: "BET", name: "Bucharest Index" }] },
  { flag: "🇬🇷", region: "GREECE", indices: [{ ticker: "GD", name: "ATHEX Composite" }] },
  { flag: "🇭🇺", region: "HUNGARY", indices: [{ ticker: "BUX", name: "Budapest Index" }] },
  { flag: "🇷🇸", region: "SERBIA", indices: [{ ticker: "BELEX15", name: "Serbia Index" }] },
  { flag: "🇯🇵", region: "JAPAN", indices: [{ ticker: "NI225", name: "Japan 225" }] },
  { flag: "🇰🇷", region: "SOUTH KOREA", indices: [{ ticker: "KOSPI", name: "Korea Composite" }] },
  { flag: "🇨🇳", region: "CHINA", indices: [
    { ticker: "000001", name: "SSE Composite" },
    { ticker: "399001", name: "Shenzhen Index" },
  ]},
  { flag: "🇭🇰", region: "HONG KONG", indices: [
    { ticker: "HSI", name: "Hang Seng" },
    { ticker: "HK33HKD", name: "Hong Kong 33" },
  ]},
  { flag: "🇸🇬", region: "SINGAPORE", indices: [{ ticker: "STI", name: "Straits Times Index" }] },
  { flag: "🇮🇩", region: "INDONESIA", indices: [
    { ticker: "COMPOSITE", name: "IDX Composite" },
    { ticker: "IDX30", name: "IDX 30" },
  ]},
  { flag: "🇲🇾", region: "MALAYSIA", indices: [{ ticker: "FBMKLCI", name: "Malaysia Index" }] },
  { flag: "🇹🇭", region: "THAILAND", indices: [{ ticker: "SET", name: "Thailand Index" }] },
  { flag: "🇮🇳", region: "INDIA", indices: [
    { ticker: "NIFTY", name: "Nifty 50" },
    { ticker: "SENSEX", name: "BSE Sensex" },
  ]},
  { flag: "🇦🇺", region: "AUSTRALIA", indices: [{ ticker: "XJO", name: "Australia 200" }] },
  { flag: "🇳🇿", region: "NEW ZEALAND", indices: [{ ticker: "NZ50G", name: "NZX 50" }] },
  { flag: "🇸🇦", region: "SAUDI ARABIA", indices: [{ ticker: "TASI", name: "Saudi Index" }] },
  { flag: "🇦🇪", region: "UAE", indices: [{ ticker: "DFMGI", name: "Dubai Index" }] },
  { flag: "🇶🇦", region: "QATAR", indices: [{ ticker: "GNRI", name: "Qatar Index" }] },
  { flag: "🇮🇱", region: "ISRAEL", indices: [{ ticker: "TA35", name: "Israel Index" }] },
  { flag: "🇪🇬", region: "EGYPT", indices: [{ ticker: "EGX30", name: "Egypt Index" }] },
  { flag: "🇿🇦", region: "SOUTH AFRICA", indices: [{ ticker: "SA40", name: "South Africa Top 40" }] },
  { flag: "🇧🇷", region: "BRAZIL", indices: [{ ticker: "IBOV", name: "Bovespa" }] },
  { flag: "🇦🇷", region: "ARGENTINA", indices: [{ ticker: "IMV", name: "MERVAL" }] },
  { flag: "🇨🇴", region: "COLOMBIA", indices: [{ ticker: "ICAP", name: "COLCAP" }] },
  { flag: "🇨🇱", region: "CHILE", indices: [{ ticker: "SP_IPSA", name: "IPSA Chile" }] },
  { flag: "🇵🇪", region: "PERU", indices: [{ ticker: "MXNUAMPEGEN", name: "Peru Index" }] },
  { flag: "🧪", region: "SECTOR INDICES", indices: [
    { ticker: "SOX", name: "PHLX Semiconductor" },
    { ticker: "HGX", name: "PHLX Housing" },
    { ticker: "OSX", name: "PHLX Oil Service" },
    { ticker: "XAU", name: "Gold/Silver Sector" },
    { ticker: "TRJEFFCRB", name: "Commodity Index" },
    { ticker: "MOVE", name: "Bond Volatility Index" },
  ]},
];
