export interface DomainInferenceResult {
  domain: string | null;
  confidence: number;
  reason: string;
}

const VERIFIED_DOMAIN_MAP: Record<string, string> = {
  TCS: "tcs.com",
  RELIANCE: "ril.com",
  INFY: "infosys.com",
  HDFCBANK: "hdfcbank.com",
  KOTAKBANK: "kotak.com",
  TRITURBINE: "trivenigroup.com",
  TTML: "tatatelebusiness.com",
  ICICIBANK: "icicibank.com",
  SBIN: "sbi.co.in",
  ITC: "itcportal.com",
  LT: "larsentoubro.com",
  AXISBANK: "axisbank.com",
  BAJFINANCE: "bajajfinserv.in",
  BHARTIARTL: "airtel.in",
  HCLTECH: "hcltech.com",
  WIPRO: "wipro.com",
  MARUTI: "marutisuzuki.com",
  SUNPHARMA: "sunpharma.com",
  MANDM: "mahindra.com",
  "M&M": "mahindra.com",
  ULTRACEMCO: "ultratechcement.com",
  NTPC: "ntpc.co.in",
  POWERGRID: "powergrid.in",
  TITAN: "titancompany.in",
  BAJAJFINSV: "bajajfinserv.in",
  ASIANPAINT: "asianpaints.com",
  NESTLEIND: "nestle.in",
  TATAMOTORS: "tatamotors.com",
  TATASTEEL: "tatasteel.com",
  HINDUNILVR: "hul.co.in",
  ADANIENT: "adani.com",
  ADANIPORTS: "adaniports.com",
  ONGC: "ongcindia.com",
  COALINDIA: "coalindia.in",
  BPCL: "bharatpetroleum.in",
  IOC: "iocl.com",
  INDUSINDBK: "indusind.com",
  TECHM: "techmahindra.com",
  CIPLA: "cipla.com",
  DRREDDY: "drreddys.com",
  APOLLOHOSP: "apollohospitals.com",
  DIVISLAB: "divislabs.com",
  BRITANNIA: "britannia.co.in",
  EICHERMOT: "eichermotors.com",
  HEROMOTOCO: "heromotocorp.com",
  JSWSTEEL: "jsw.in",
  GRASIM: "grasim.com",
  HINDALCO: "hindalco.com",
  TATACONSUM: "tataconsumer.com",
  UPL: "upl-ltd.com",
  ADANIGREEN: "adanigreenenergy.com",
  ADANIPOWER: "adani.com",
  ADANITRANS: "adani.com",
  GODREJCP: "godrejcp.com",
  DABUR: "dabur.com",
  PIDILITIND: "pidilite.com",
  BAJAJ_AUTO: "bajajauto.com",
  HDFCLIFE: "hdfclife.com",
  SBILIFE: "sbilife.co.in",
  ICICIPRULI: "iciciprulife.com",
  SHREECEM: "shreecement.com",
  AMBUJACEM: "ambujacement.com",
  ACC: "acclimited.com",
  SIEMENS: "siemens.co.in",
  BEL: "bel-india.in",
  HAL: "hal-india.co.in",
  IRCTC: "irctc.co.in",
  DMART: "avenuesupermarts.com",
  ZOMATO: "zomato.com",
  PAYTM: "paytm.com",
  NYKAA: "nykaa.com",
  POLICYBZR: "policybazaar.com",
  MOTHERSON: "motherson.com",
  LUPIN: "lupin.com",
  AUROPHARMA: "aurobindo.com",
  BIOCON: "biocon.com",
  PNB: "pnbindia.in",
  BANKBARODA: "bankofbaroda.in",
  CANBK: "canarabank.com",
  UNIONBANK: "unionbankofindia.co.in",
  IDFCFIRSTB: "idfcfirstbank.com",
  FEDERALBNK: "federalbank.co.in",
  BHEL: "bhel.com",
  GAIL: "gailonline.com",
  TVSMOTOR: "tvsmotor.com",
  BOSCHLTD: "bosch.in",
  MRF: "mrf.co.in",
  INDIGO: "goindigo.in",
  LICI: "licindia.in",
  CHOLAFIN: "cholamandalam.com",
  SRF: "srf.com",
  PAGEIND: "pageind.com",
  HAVELLS: "havells.com",
  BERGEPAINT: "bergerpaints.com",
  NAUKRI: "infoedge.in",
  IRFC: "irfc.co.in",
  RVNL: "rvnl.org",
  PFC: "pfcindia.com",
  RECLTD: "recindia.nic.in",
  TRENT: "trentlimited.com",
  AAPL: "apple.com",
  MSFT: "microsoft.com",
  GOOGL: "abc.xyz",
  GOOG: "abc.xyz",
  AMZN: "amazon.com",
  META: "meta.com",
  NVDA: "nvidia.com",
  TSLA: "tesla.com",
  BRK: "berkshirehathaway.com",
  JPM: "jpmorganchase.com",
  V: "visa.com",
  MA: "mastercard.com",
  WMT: "walmart.com",
  XOM: "exxonmobil.com",
  PG: "pg.com",
  JNJ: "jnj.com",
  UNH: "unitedhealthgroup.com",
  HD: "homedepot.com",
  BAC: "bankofamerica.com",
  KO: "coca-colacompany.com",
  PEP: "pepsico.com",
  AVGO: "broadcom.com",
  COST: "costco.com",
  ADBE: "adobe.com",
  CRM: "salesforce.com",
  ORCL: "oracle.com",
  NFLX: "netflix.com",
  CSCO: "cisco.com",
  DIS: "thewaltdisneycompany.com",
  ABBV: "abbvie.com",
  MRK: "merck.com",
  CVX: "chevron.com",
  AMD: "amd.com",
  INTC: "intel.com",
  QCOM: "qualcomm.com",
  TMO: "thermofisher.com",
  LIN: "linde.com",
  NKE: "nike.com",
  DHR: "danaher.com",
  MCD: "mcdonalds.com",
  RTX: "rtx.com",
  CAT: "cat.com",
  UPS: "ups.com",
  IBM: "ibm.com",
  GE: "ge.com",
  GS: "goldmansachs.com",
  MS: "morganstanley.com",
  AMAT: "amat.com",
  TXN: "ti.com",
  AMGN: "amgen.com",
  INTU: "intuit.com",
  BKNG: "bookingholdings.com",
  SBUX: "starbucks.com"
};

function normalizeSymbol(symbol: string): string {
  return symbol.trim().toUpperCase();
}

function extractBaseSymbol(symbol: string): string {
  return normalizeSymbol(symbol).split(/[-.$]/)[0] || normalizeSymbol(symbol);
}

export function inferDomainWithConfidence(input: { symbol: string; name: string; exchange?: string }): DomainInferenceResult {
  const normalized = normalizeSymbol(input.symbol);
  const base = extractBaseSymbol(normalized);

  const exact = VERIFIED_DOMAIN_MAP[normalized];
  if (exact) {
    return { domain: exact, confidence: 0.99, reason: "verified_symbol_map" };
  }

  const baseMatch = VERIFIED_DOMAIN_MAP[base];
  if (baseMatch) {
    return { domain: baseMatch, confidence: 0.98, reason: "verified_base_symbol_map" };
  }

  return { domain: null, confidence: 0, reason: "no_trusted_source" };
}
