/**
 * TV-Parity 500 Tests — POLYLINE shape
 *
 * 2-anchor drag — open polyline (mid-points generated by stroke).
 * Rail: rail-brush
 * testId: tool-polyline
 */

import { registerExtendedSuite } from "./tv-parity-extended-factory";

registerExtendedSuite({
  variant: "polyline",
  testId: "tool-polyline",
  railTestId: "rail-brush",
  kind: "shape",
  anchorCount: 2,
  commitMode: "drag",
});
