export const STATIC_DOMAIN_MAP: Record<string, string> = {
  TCS: "tcs.com",
  RELIANCE: "ril.com",
  INFY: "infosys.com",
  HDFCBANK: "hdfcbank.com",
  KOTAKBANK: "kotak.com",
  TRITURBINE: "trivenigroup.com",
  TTML: "tatatelebusiness.com",
  ICICIBANK: "icicibank.com",
  SBIN: "sbi.co.in",
  ITC: "itcportal.com",
  LT: "larsentoubro.com",
  AXISBANK: "axisbank.com",
  BAJFINANCE: "bajajfinserv.in",
  BHARTIARTL: "airtel.in",
  HCLTECH: "hcltech.com",
  WIPRO: "wipro.com",
  MARUTI: "marutisuzuki.com",
  SUNPHARMA: "sunpharma.com",
  MANDM: "mahindra.com",
  ULTRACEMCO: "ultratechcement.com",
  NTPC: "ntpc.co.in",
  POWERGRID: "powergrid.in",
  TITAN: "titancompany.in",
  ASIANPAINT: "asianpaints.com",
  TATAMOTORS: "tatamotors.com",
  TATASTEEL: "tatasteel.com",
  HINDUNILVR: "hul.co.in",
  ADANIENT: "adani.com",
  ADANIPORTS: "adaniports.com",
  ONGC: "ongcindia.com",
  COALINDIA: "coalindia.in",
  BPCL: "bharatpetroleum.in",
  IOC: "iocl.com",
  TECHM: "techmahindra.com",
  CIPLA: "cipla.com",
  DRREDDY: "drreddys.com",
  APOLLOHOSP: "apollohospitals.com",
  DIVISLAB: "divislabs.com",
  BRITANNIA: "britannia.co.in",
  EICHERMOT: "eichermotors.com",
  HEROMOTOCO: "heromotocorp.com",
  JSWSTEEL: "jsw.in",
  GRASIM: "grasim.com",
  HINDALCO: "hindalco.com",
  PNB: "pnbindia.in",
  BANKBARODA: "bankofbaroda.in",
  CANBK: "canarabank.com",
  BHEL: "bhel.com",
  GAIL: "gailonline.com",
  TVSMOTOR: "tvsmotor.com",
  INDIGO: "goindigo.in",
  LICI: "licindia.in",
  HAVELLS: "havells.com",
  BERGEPAINT: "bergerpaints.com",
  IRFC: "irfc.co.in",
  RVNL: "rvnl.org",
  AAPL: "apple.com",
  MSFT: "microsoft.com",
  GOOGL: "abc.xyz",
  GOOG: "abc.xyz",
  AMZN: "amazon.com",
  META: "meta.com",
  NVDA: "nvidia.com",
  TSLA: "tesla.com",
  BRK: "berkshirehathaway.com",
  JPM: "jpmorganchase.com",
  V: "visa.com",
  MA: "mastercard.com",
  WMT: "walmart.com",
  XOM: "exxonmobil.com",
  PG: "pg.com",
  JNJ: "jnj.com",
  UNH: "unitedhealthgroup.com",
  HD: "homedepot.com",
  BAC: "bankofamerica.com",
  KO: "coca-colacompany.com",
  PEP: "pepsico.com",
  AVGO: "broadcom.com",
  COST: "costco.com",
  ADBE: "adobe.com",
  CRM: "salesforce.com",
  ORCL: "oracle.com",
  NFLX: "netflix.com",
  CSCO: "cisco.com",
  DIS: "thewaltdisneycompany.com",
  ABBV: "abbvie.com",
  MRK: "merck.com",
  CVX: "chevron.com",
  AMD: "amd.com",
  INTC: "intel.com",
  QCOM: "qualcomm.com",
  NKE: "nike.com",
  MCD: "mcdonalds.com",
  CAT: "cat.com",
  UPS: "ups.com",
  IBM: "ibm.com",
  GS: "goldmansachs.com",
  AMGN: "amgen.com",
  INTU: "intuit.com",
  SBUX: "starbucks.com"
};

function normalizeSymbol(symbol: string): string {
  return symbol.trim().toUpperCase();
}

function extractBaseSymbol(symbol: string): string {
  return normalizeSymbol(symbol).split(/[-.$]/)[0] || normalizeSymbol(symbol);
}

export function getStaticDomain(symbol: string): string | null {
  const normalized = normalizeSymbol(symbol);
  const base = extractBaseSymbol(normalized);
  return STATIC_DOMAIN_MAP[normalized] || STATIC_DOMAIN_MAP[base] || null;
}
